In [15]:
import os
import numpy

In [16]:
file = os.path.join('data', 'water.xyz')
data = numpy.genfromtxt(fname = file, dtype = 'unicode', skip_header = 2)
print(data)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [17]:
atoms = data[:,0]
print(atoms)

['O' 'H1' 'H2']


In [18]:
coord = data[:,1:].astype(numpy.float)
print(coord)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [36]:
for i in range(len(atoms)):
    for j in range(len(atoms)):
        dist = numpy.sqrt(numpy.sum(numpy.square(coord[i] - coord[j])))
        print(F'{atoms[i]} to {atoms[j]}: {dist:.3f}')

O to O: 0.000
O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H1 to H1: 0.000
H1 to H2: 1.527
H2 to O: 0.969
H2 to H1: 1.527
H2 to H2: 0.000
